### ISSUE TITLE
issue: exception of `invalid load key, 'v'.`

### ISSUE THREAD

**Issue by ltdrdata** [mlinmg/ComfyUI-LaMA-Preprocessor#1]
Did I just replace the model in your workflow, or is this require a specific VAE model?

![lama](https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/128333288/c1d7c940-0b38-42fa-8a59-99dcba0abd8d)

```
got prompt
invalid load key, 'v'.
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/home/me/git/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/ComfyUI/custom_nodes/ComfyUI-LaMA-Preprocessor/inpaint_Lama.py", line 497, in preprocess
    raise e
  File "/home/me/git/ComfyUI/custom_nodes/ComfyUI-LaMA-Preprocessor/inpaint_Lama.py", line 493, in preprocess
    prd_color = model_lama(image_res)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/ComfyUI/custom_nodes/ComfyUI-LaMA-Preprocessor/annotator/lama/__init__.py", line 53, in __call__
    self.load_model()
  File "/home/me/git/ComfyUI/custom_nodes/ComfyUI-LaMA-Preprocessor/annotator/lama/__init__.py", line 42, in load_model
    self.model = load_checkpoint(cfg, os.path.abspath(modelpath), strict=False, map_location='cpu')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/ComfyUI/custom_nodes/ComfyUI-LaMA-Preprocessor/annotator/lama/saicinpainting/training/trainers/__init__.py", line 27, in load_checkpoint
    state = torch.load(path, map_location=map_location)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/ComfyUI/venv/lib/python3.11/site-packages/torch/serialization.py", line 1030, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/git/ComfyUI/venv/lib/python3.11/site-packages/torch/serialization.py", line 1248, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.

Prompt executed in 0.84 seconds
```

**Comment by ltdrdata** [comment]
oh.. I found that internal model loading code..
But it seems that doesn't download model, properly.

**Comment by ltdrdata** [comment]
It seems like the file `annotator/lama/models/lama/lama/ControlNetLama.pth` already exists in your repo, and it might be a symbolic link created by you.

The file's existence is causing the file download to be skipped.

**Comment by mlinmg** [comment]
Sorry I forgot to write to install with git lfs
