### ISSUE TITLE
name '_load_file_from_url' is not defined

### ISSUE THREAD

**Issue by Xiahussheng** [mlinmg/ComfyUI-LaMA-Preprocessor#17]
I'm sorry, but after I updated comfyui and this extension
It still reports an error and I don't know how to deal with it.

-----------------------------------------------------------------------------------------

Error occurred when executing lamaPreprocessor:

name '_load_file_from_url' is not defined

File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 387, in preprocess
raise e
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 383, in preprocess
prd_color = model_lama(image_res)
^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\annotator\lama\__init__.py", line 57, in __call__
self.load_model()
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\annotator\lama\__init__.py", line 40, in load_model
_load_file_from_url(remote_model_path, model_dir=self.model_dir)
^^^^^^^^^^^^^^^^^^^

--------------------------------------------------------------------------------------------------

name '_load_file_from_url' is not defined
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 387, in preprocess
    raise e
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 383, in preprocess
    prd_color = model_lama(image_res)
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\annotator\lama\__init__.py", line 57, in __call__
    self.load_model()
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\annotator\lama\__init__.py", line 40, in load_model
    _load_file_from_url(remote_model_path, model_dir=self.model_dir)
    ^^^^^^^^^^^^^^^^^^^
NameError: name '_load_file_from_url' is not defined

**Comment by mlinmg** [comment]
now is fixed, thanks for the report

**Comment by Xiahussheng** [comment]
it works now，thanks a lot
