### ISSUE TITLE
 cannot access local variable 'final_img_with_alpha' where it is not associated with a value

### ISSUE THREAD

**Issue by huanhuachenfeng** [mlinmg/ComfyUI-LaMA-Preprocessor#26]
This error is very strange, **I was using it normally one second, and the next time I executed the queue, it showed this error.**

```python
Error occurred when executing lamaPreprocessor:

cannot access local variable 'final_img_with_alpha' where it is not associated with a value

File "E:\Comfyui\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfyui\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\Comfyui\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 449, in preprocess
final_img = get_pytorch_control(final_img_with_alpha)
```

**Comment by huanhuachenfeng** [comment]
error in cmd:

```python
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\Comfyui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Comfyui\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 449, in preprocess
    final_img = get_pytorch_control(final_img_with_alpha)
                                    ^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'final_img_with_alpha' where it is not associated with a value

Prompt executed in 0.08 seconds
```

**Comment by huanhuachenfeng** [comment]
I found the problem, my error operation:
I connected the mask on the lamaPreprocessor node to the image loading node
