### ISSUE TITLE
Does this node only support NVIDIA GPU?

### ISSUE THREAD

**Issue by amimi818** [mlinmg/ComfyUI-LaMA-Preprocessor#6]
**Describe the bug**
Macbook, MacOS

error log：

got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/Users/wyj/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/wyj/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/wyj/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/wyj/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/ComfyUI-LaMA-Preprocessor/inpaint_Lama.py", line 410, in preprocess
    encoded_image = self._encode_image(vae, final_img)
  File "/Users/wyj/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/ComfyUI-LaMA-Preprocessor/inpaint_Lama.py", line 302, in _encode_image
    encoded_image = wrapper.encode_first_stage_(image)
  File "/Users/wyj/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/wyj/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/ComfyUI-LaMA-Preprocessor/inpaint_Lama.py", line 270, in encode_first_stage_
    self.to(torch.device('cuda'))
  File "/Users/wyj/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/ComfyUI-LaMA-Preprocessor/inpaint_Lama.py", line 250, in to
    self.vae.first_stage_model.to(where)
  File "/Users/wyj/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/Users/wyj/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/wyj/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/wyj/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/Users/wyj/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/Users/wyj/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

<img width="2049" alt="image" src="https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/assets/133093934/5c3a9ee6-33c1-4713-ad40-6ab88d72c02d">

**Comment by mlinmg** [comment]
Yes thank you for pointing it out. If you're intrested you can modify it to make it mac os safe and make a pull request.
to do so, every time there is a numpy manipolation you have to copy the array twice(idk why but in the original code they seem to do this)
