### ISSUE TITLE
Broken example workflow?

### ISSUE THREAD

**Issue by EvgeneKuklin** [mlinmg/ComfyUI-LaMA-Preprocessor#7]
Example workflow throws en error after running it with horisontal expansion 128:
```
Traceback (most recent call last):
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 425, in preprocess
    _, img = apply_border_noise(img_non_black, 'inpainting', mask, h, w)
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 245, in apply_border_noise
    result[mask, 3] = 255.0
IndexError: boolean index did not match indexed array along dimension 1; dimension is 512 but corresponding boolean dimension is 640
```

With vertical expansion 128:
```
Traceback (most recent call last):
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 416, in preprocess
    raise e
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 412, in preprocess
    prd_color = model_lama(image_res)
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\annotator\lama\__init__.py", line 52, in __call__
    self.load_model()
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\annotator\lama\__init__.py", line 34, in load_model
    from basicsr.utils.download_util import load_file_from_url
ModuleNotFoundError: No module named 'basicsr'
```

**Additional context**
Image that I used was 512x768
I have not been able to run the preprocessor at all
Maybe i'm doing something wrong?

**Comment by mlinmg** [comment]
You have to install basicsr with your python interpreter

**Comment by mlinmg** [comment]
Try to install it with the manager, it automatically installs dependencies

**Comment by EvgeneKuklin** [comment]
The problem is that I actually installed it with the manager.
And when I try to install basicsr manually I got this:
```
F:\AI\ComfyUI\update>..\python_embeded\python.exe -s -m pip install basicsr
Collecting basicsr
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: addict in f:\ai\comfyui\python_embeded\lib\site-packages (from basicsr) (2.4.0)
Collecting future (from basicsr)
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Admin\AppData\Local\Temp\pip-install-ibkorw7h\future_ef464d5fbb60420e892aaaec3c10e819\setup.py", line 86, in <module>
          import src.future
      ModuleNotFoundError: No module named 'src'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mlinmg** [comment]
Try ti install src and then basic

**Comment by EvgeneKuklin** [comment]
> Try to install src and then basic

```
F:\AI\ComfyUI\update>..\python_embeded\python.exe -s -m pip install src
Collecting src
  Downloading src-0.0.7.zip (6.3 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: src
  Building wheel for src (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\src
      copying src\__init__.py -> build\lib\src
      running egg_info
      writing src.egg-info\PKG-INFO
      writing dependency_links to src.egg-info\dependency_links.txt
      deleting src.egg-info\entry_points.txt
      writing requirements to src.egg-info\requires.txt
      writing top-level names to src.egg-info\top_level.txt
      reading manifest file 'src.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.rst'
      writing manifest file 'src.egg-info\SOURCES.txt'
      F:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\_distutils\dist.py:947: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        command.initialize_options()
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Admin\AppData\Local\Temp\pip-install-qizt5bdz\src_850caec541ad42659e1b20dda383ff1e\setup.py", line 70, in <module>
          setup(
        File "F:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "F:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "F:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "F:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "F:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "F:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "F:\AI\ComfyUI\python_embeded\lib\site-packages\wheel\bdist_wheel.py", line 366, in run
          install = self.reinitialize_command("install", reinit_subcommands=True)
        File "F:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\__init__.py", line 216, in reinitialize_command
          cmd = _Command.reinitialize_command(self, command, reinit_subcommands)
        File "F:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\_distutils\cmd.py", line 311, in reinitialize_command
          return self.distribution.reinitialize_command(command, reinit_subcommands)
        File "F:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\_distutils\dist.py", line 953, in reinitialize_command
          for sub in command.get_sub_commands():
        File "F:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\_distutils\cmd.py", line 329, in get_sub_commands
          if method is None or method(self):
        File "F:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\_distutils\command\install.py", line 787, in has_lib
          self.distribution.has_pure_modules() or self.distribution.has_ext_modules()
      AttributeError: 'NoneType' object has no attribute 'has_pure_modules'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for src
  Running setup.py clean for src
Failed to build src
ERROR: Could not build wheels for src, which is required to install pyproject.toml-based projects
```


Maybe I should use specific version?

**Comment by mlinmg** [comment]
It's very strange. Try to eliminate the folder and then reinstall the node

**Comment by EvgeneKuklin** [comment]
> It's very strange. Try to eliminate the folder and then reinstall the node

The same problem...

**Comment by EvgeneKuklin** [comment]
Alright, the fix of problem with is:

Replacing basicsr's load_file_from_url with:

```
import urllib.request
def download_model(model_path: str, model_dir: str) -> None:
    os.makedirs(os.path.dirname(model_dir), exist_ok=True)
    urllib.request.urlretrieve(model_path, os.path.join(model_dir, model_path.split("/")[-1]))
```

And then the preprocessor downloads models and works
But, when I try to use it without any vertical_expansion I get an error:
```
ERROR:root:Traceback (most recent call last):
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 425, in preprocess
    _, img = apply_border_noise(img_non_black, 'inpainting', mask, h, w)
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor\inpaint_Lama.py", line 245, in apply_border_noise
    result[mask, 3] = 255.0
IndexError: boolean index did not match indexed array along dimension 1; dimension is 512 but corresponding boolean dimension is 520
```

When I use minimal vertical_expansion it is working fine, and with horisontal one there is no such issue

**Comment by mlinmg** [comment]
Please share your workflow and image otherwise is impossibile to check the bug. Open a new issue so we can track efficently that
